-- 065. Find usage of Database Indexes - SQL Server Script

SELECT   
	OBJECT_NAME(DDIUS.OBJECT_ID) AS [OBJECT NAME]
	 ,I.[NAME] AS IndexName
	 ,USER_SEEKS AS TotalUserSeek
	 ,USER_SCANS AS TotalUserScan
	 ,USER_LOOKUPS AS TotalUserLookup
	 ,USER_UPDATES AS TotalUserUpdate
FROM SYS.DM_DB_INDEX_USAGE_STATS AS DDIUS
INNER JOIN SYS.INDEXES AS I 
	ON I.OBJECT_ID = DDIUS.OBJECT_ID
	AND I.INDEX_ID = DDIUS.INDEX_ID 
WHERE OBJECTPROPERTY(DDIUS.OBJECT_ID,'IsUserTable') = 1
