-- 066. Find Index Operational Stats - SQL Server Script

SELECT 
	OBJECT_NAME(DDIOS.OBJECT_ID) AS ObjectName
	,I.[NAME] AS IndexName
	,DDIOS.LEAF_INSERT_COUNT AS TotalInsertCount
	,DDIOS.LEAF_UPDATE_COUNT AS TotalUpdateCount
	,DDIOS.LEAF_DELETE_COUNT AS TotalDeleteCount
FROM SYS.DM_DB_INDEX_OPERATIONAL_STATS (NULL,NULL,NULL,NULL ) AS DDIOS
INNER JOIN SYS.INDEXES AS I 
	ON I.OBJECT_ID = DDIOS.OBJECT_ID
	AND I.INDEX_ID = DDIOS.INDEX_ID 
WHERE  OBJECTPROPERTY(DDIOS.OBJECT_ID,'IsUserTable') = 1
