-- 079. SQL Server Script to kill all processes for Database  

DECLARE @EXECSQL VARCHAR(1000)
DECLARE @DBNAME VARCHAR(100)

SET @DBNAME = 'MvcMovies'
SET @EXECSQL = ''

SELECT  @EXECSQL = @EXECSQL + 'KILL ' + CONVERT(CHAR(10), SPID) + ' '
FROM    MASTER.DBO.SYSPROCESSES
WHERE   DB_NAME(DBID) = @DBNAME
AND  DBID <> 0  AND  SPID <> @@SPID

PRINT @EXECSQL

EXEC(@EXECSQL)
